site_name: Data Structures & Algorithms in Python
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/anujonthemove/Data-Structures-and-Algorithms-Python/
repo_name: anujonthemove/Data-Structures-and-Algorithms-Python



# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand

  palette:
    primary: yellow
    # accent: indigo
  font:
    text: Roboto Mono

    # # Palette toggle for light mode
    # - scheme: default
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode


markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      # base_path: docs/snippets

plugins:
  - mkdocs-jupyter:
  - search

nav:
  - Home: 'index.md'
  - 'Linked List':
  
    - '0. Linked List Template': 'notebooks/linked-list-template.ipynb'
    - '1. Singly Linked List': 'notebooks/singly-linked-list.ipynb'
    - '2. Doubly Linked List': 'notebooks/doubly-linked-list.ipynb'
  - 'Stack':

    - '1. Stack using Python List': 'notebooks/stack-using-list.ipynb'
    - '2. Stack using Linked List': 'notebooks/stack-using-linked-list.ipynb'
    - '3. Infix to Postfix expression': 'notebooks/infix-to-postfix-conversion.ipynb'
    - '4. Infix to Prefix expression': 'notebooks/infix-to-prefix-expression.ipynb'
    - '5. Postfix to Infix expression': 'notebooks/postfix-to-infix-expression.ipynb'
    - '6. Prefix to Infix expression': 'notebooks/prefix-to-infix-expression.ipynb'
    - '7. Evaluation of Postfix expression': 'notebooks/evaluation-of-postfix-expression.ipynb'
    - '8. Evaluation of Prefix expression': 'notebooks/evaluation-of-prefix-expression.ipynb'

  - 'Recursion':
    - 'Bubble Sort': 'notebooks/bubble-sort.ipynb' 