name: ci 


on:
  push:
    branches: 
      - main

  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      # - uses: actions/cache@v2
      #   with:
      #       key: ${{ github.ref }}
      #       path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-jupyter
      - run: pip install pillow cairosvg
      - run: pip install jupyter_contrib_nbextensions
      # - run: mkdir -p docs/notebooks/recursion
      # - run: cp -r notebooks/recursion/*.ipynb docs/ # copy all notebooks to docs folder
      #- run: cp README.md docs/index.md
      - run: mkdocs gh-deploy --force
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

